version: '3.9'

services:
  server:
    container_name: minecraft-server
    build: .
    volumes:
      - ./artifacts:/home/minecraft
    ports:
      - 25565:25565
    command: java -Xmx2G -jar server.jar --nogui
    deploy:
      resources:
        limits:
          memory: 2G